### ISSUE TITLE
Suggestion for i3startup

### ISSUE THREAD

**Issue by JanKaifer** [sLite/i3-config#1]
Hey,
first of all thanks for putting your dotfiles online with nice read.me.
Also, you use this in your i3startup script:
`
i3
read
`
But I believe that using `exec` is a better solution:
`
exec i3
`
a) It does the same thing.
b) When i3 fails to start `i3startup` ends
c) When you kill i3 `i3startup` ends - won't hang in the background

Anyway thanks again.

**Comment by sLite** [comment]
Thanks for the tip, i will incorporate that :)
